#run with "docker-compose up"
version: '3'
services:
  rest:
    build: ./rest
    volumes:
      - ./rest:/usr/src/rest
    links:
      - ipfs_host
    ports:
      - "8081:8081"
    environment:
      - FLASK_ENV=development
    depends_on:
      - ipfs_host
  
  ipfs_host:
    build: ./ipfs
    # Note, I have not mount a directory for this demonstration, so everytime we restart
    # the container is empty again
    # volumes:  
    #   - $ipfs_staging:/export
    #   - $ipfs_data:/data/ipfs
    ports:  # host port:container port
      - "127.0.0.1:5001:5001"
      - "4001:4001"
      - "127.0.0.1:8080:8080" 